version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/usr/src/app/uploads
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    restart: unless-stopped
